export const SUFFIX_START = '_start';
export const SUFFIX_SUCCESS = '_success';
export const SUFFIX_FAILED = '_failed';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_START = `${FETCH_POSTS}${SUFFIX_START}`;
export const FETCH_POSTS_SUCCESS = `${FETCH_POSTS}${SUFFIX_SUCCESS}`;
export const FETCH_POSTS_FAILED = `${FETCH_POSTS}${SUFFIX_FAILED}`;

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_START = `${FETCH_POST}${SUFFIX_START}`;
export const FETCH_POST_SUCCESS = `${FETCH_POST}${SUFFIX_SUCCESS}`;
export const FETCH_POST_FAILED = `${FETCH_POST}${SUFFIX_FAILED}`;

export const SUBMIT_POST_FORM = 'SUBMIT_POST_FORM';
export const SUBMIT_POST_FORM_START = `${SUBMIT_POST_FORM}${SUFFIX_START}`;
export const SUBMIT_POST_FORM_SUCCESS = `${SUBMIT_POST_FORM}${SUFFIX_SUCCESS}`;
export const SUBMIT_POST_FORM_FAILED = `${SUBMIT_POST_FORM}${SUFFIX_FAILED}`;

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_START = `${DELETE_POST}${SUFFIX_START}`;
export const DELETE_POST_SUCCESS = `${DELETE_POST}${SUFFIX_SUCCESS}`;
export const DELETE_POST_FAILED = `${DELETE_POST}${SUFFIX_FAILED}`;
